package com.msahil432.sms.common;

public enum Event {
  PROFILE_DETAILS_DONE,
  CITIES_SELECTED,

  VIEW_PRODUCT,

  PRODUCT_DETAILS_DONE,
  PRODUCT_PICS_DONE,
  PRODUCT_REMOVE,

  VIEW_QUOTATION,
  ACCEPT_QUOTATION,
  DECLINE_QUOTATION,

  ORDER_VIEW,
  ORDER_UPDATE,
  ORDER_DELETE
}